#!/bin/bash
 
BREAK_CHARS="(){}[],^%$#@\"\";:''|\\"
CLOJURE_DIR=/usr/share/java/
CLOJURE_JAR=$CLOJURE_DIR/clojure.jar
if [ $# -eq 0 ]; then 
     rlwrap --remember -c -b $BREAK_CHARS -f $HOME/.clj_completions \
     java -cp $CLOJURE_JAR clojure.main
else
     java -cp $CLOJURE_JAR clojure.main $1 -- $@
fi
